version: '3'
services:
  music_focus_web:
    environment:
      TZ: Asia/Shanghai
      POSTS_URL: http://172.31.222.85:8000/api/v1/posts
      FOCUSES_URL: http://172.31.222.85:8000/api/v1/focuses
      VIDEOS_URL:  http://172.31.222.85:8000/api/v1/videos
    ports:
      - 9000:8000
    image: music_focus_web:latest
    volumes:
      - ../music_focus/data/weibo_images:/music_focus_web/app/static/images/weibo
      - ../music_focus/data/video_covers:/music_focus_web/app/static/images/video_cover
      - ./log://music_focus_web/log
    restart: always
